// Generated by tools/ui-parity/extract-icons.mjs from the mockup's symbols; don't edit, re-run it.
using System.Collections.Generic;

namespace MountainPlanner.UI.Hud
{
    /// <summary>Each HUD symbol's layers, bottom first: the vector image's name under Resources/HudIcons, and whether it's a knock-out.</summary>
    public static class HudIconLayers
    {
        public readonly struct Layer
        {
            public readonly string Image;
            public readonly bool Knock;
            public Layer(string image, bool knock) { Image = image; Knock = knock; }
        }

        public static readonly Dictionary<string, Layer[]> All = new Dictionary<string, Layer[]>
        {
            ["s-hammer"] = new[] { new Layer("s-hammer", false) },
            ["s-analysis"] = new[] { new Layer("s-analysis", false) },
            ["s-play"] = new[] { new Layer("s-play", false) },
            ["s-pause"] = new[] { new Layer("s-pause", false) },
            ["s-speed"] = new[] { new Layer("s-speed", false) },
            ["s-cash"] = new[] { new Layer("s-cash", false) },
            ["s-lift"] = new[] { new Layer("s-lift", false) },
            ["s-skier"] = new[] { new Layer("s-skier", false) },
            ["s-gun"] = new[] { new Layer("s-gun", false) },
            ["s-pipe"] = new[] { new Layer("s-pipe", false) },
            ["s-pump"] = new[] { new Layer("s-pump.0", false), new Layer("s-pump.1", true) },
            ["s-lodge"] = new[] { new Layer("s-lodge.0", false), new Layer("s-lodge.1", true), new Layer("s-lodge.2", false) },
            ["s-road"] = new[] { new Layer("s-road.0", false), new Layer("s-road.1", true) },
            ["s-parking"] = new[] { new Layer("s-parking.0", false), new Layer("s-parking.1", true) },
            ["s-save"] = new[] { new Layer("s-save", false) },
            ["s-pencil"] = new[] { new Layer("s-pencil", false) },
            ["s-map"] = new[] { new Layer("s-map", false) },
            ["s-menu"] = new[] { new Layer("s-menu", false) },
            ["s-flake"] = new[] { new Layer("s-flake", false) },
            ["s-trail"] = new[] { new Layer("s-trail.0", false), new Layer("s-trail.1", true) },
            ["s-camera"] = new[] { new Layer("s-camera.0", false), new Layer("s-camera.1", true), new Layer("s-camera.2", false) },
            ["s-hide"] = new[] { new Layer("s-hide.0", false), new Layer("s-hide.1", true), new Layer("s-hide.2", false), new Layer("s-hide.3", true), new Layer("s-hide.4", false) },
            ["b-new"] = new[] { new Layer("b-new.0", true), new Layer("b-new.1", false), new Layer("b-new.2", true) },
            ["b-edit"] = new[] { new Layer("b-edit.0", true), new Layer("b-edit.1", false), new Layer("b-edit.2", true) },
            ["b-remove"] = new[] { new Layer("b-remove.0", true), new Layer("b-remove.1", false), new Layer("b-remove.2", true) },
        };
    }
}
