// The HUD's symbols, from the mockup (task P2-02): every <symbol> in docs/plans/prototypes/ui-layout.html becomes
// white SVG layers under Assets/MountainPlanner/Art/UI/Icons/Resources/HudIcons/, imported as UI Toolkit vector
// images (Editor/HudIconImport.cs), plus the C# table that stacks them (Runtime/UI/Hud/HudIconLayers.g.cs).
// The mockup draws each symbol in the text colour, with knock-outs painted in the panel colour (var(--knock)); the
// game does the same with two kinds of layer, tinted at run time: base layers take the icon's text colour, knock
// layers the colour behind the icon (HudIcon). Consecutive shapes of one kind share a layer, in drawing order.
// Re-run after changing a symbol in the mockup: node tools/ui-parity/extract-icons.mjs
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const html = readFileSync(path.join(root, 'docs/plans/prototypes/ui-layout.html'), 'utf8');
const outDir = path.join(root, 'Assets/MountainPlanner/Art/UI/Icons/Resources/HudIcons');
const table = path.join(root, 'Assets/MountainPlanner/Runtime/UI/Hud/HudIconLayers.g.cs');

// The top-level elements of a symbol's body, each with its children (balanced tags).
function topLevel(body) {
  const parts = [];
  const re = /<\/?([a-z]+)\b[^>]*?(\/?)>/gi;
  let depth = 0, start = -1, m;
  while ((m = re.exec(body))) {
    const closing = m[0].startsWith('</'), selfClosing = m[2] === '/';
    if (!closing && depth === 0) start = m.index;
    if (!closing && !selfClosing) depth++;
    if (closing) depth--;
    if (depth === 0) parts.push(body.slice(start, re.lastIndex));
  }
  return parts;
}

const knocked = (el) => /var\(--knock\)/.test(el.match(/^<[^>]*>/)[0]);
const white = (el) => el
  .replace(/style="fill:var\(--knock\)"/g, 'fill="#ffffff"')
  .replace(/style="stroke:var\(--knock\)"/g, 'stroke="#ffffff"')
  .replace(/currentColor/g, '#ffffff');

const symbols = [...html.matchAll(/<symbol id="([^"]+)" viewBox="([^"]+)">([\s\S]*?)<\/symbol>/g)];
if (!symbols.length) throw new Error('no <symbol> found in the mockup');
mkdirSync(outDir, { recursive: true });
const keep = new Set();
const rows = [];
for (const [, id, viewBox, body] of symbols) {
  const [, , w, h] = viewBox.split(/\s+/).map(Number);
  const layers = [];
  for (const el of topLevel(body)) {
    if (/var\(--knock\)/.test(el) && !knocked(el)) throw new Error(`${id}: a knock-out inside a drawn shape can't be layered`);
    const kind = knocked(el);
    if (!layers.length || layers[layers.length - 1].knock !== kind) layers.push({ knock: kind, els: [] });
    layers[layers.length - 1].els.push(white(el));
  }
  layers.forEach((layer, i) => {
    const name = layers.length === 1 ? id : `${id}.${i}`;
    const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="${viewBox}"><g fill="#ffffff">${layer.els.join('')}</g></svg>\n`;
    writeFileSync(path.join(outDir, `${name}.svg`), svg);
    keep.add(`${name}.svg`);
    layer.name = name;
  });
  rows.push(`            ["${id}"] = new[] { ${layers.map((l) => `new Layer("${l.name}", ${l.knock ? 'true' : 'false'})`).join(', ')} },`);
}
// Symbols that left the mockup leave the game too (their .meta with them).
for (const f of readdirSync(outDir)) {
  const svg = f.replace(/\.meta$/, '');
  if (svg.endsWith('.svg') && !keep.has(svg)) rmSync(path.join(outDir, f));
}

mkdirSync(path.dirname(table), { recursive: true });
writeFileSync(table, `// Generated by tools/ui-parity/extract-icons.mjs from the mockup's symbols; don't edit, re-run it.
using System.Collections.Generic;

namespace MountainPlanner.UI.Hud
{
    /// <summary>Each HUD symbol's layers, bottom first: the vector image's name under Resources/HudIcons, and whether it's a knock-out.</summary>
    public static class HudIconLayers
    {
        public readonly struct Layer
        {
            public readonly string Image;
            public readonly bool Knock;
            public Layer(string image, bool knock) { Image = image; Knock = knock; }
        }

        public static readonly Dictionary<string, Layer[]> All = new Dictionary<string, Layer[]>
        {
${rows.join('\n')}
        };
    }
}
`.replace(/\n/g, '\r\n'));
console.log(`${symbols.length} symbols, ${keep.size} layers -> ${path.relative(root, outDir)}`);
